spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nombre_de_tu_base
    username: tu_usuario
    password: tu_contraseña
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
